[project]
name = "stackodds"
description = "Prototype LMSR-style prediction market on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.token]
path = "contracts/token.clar"
epoch = 2.1

[contracts.contract]
path = "contracts/contract.clar"
epoch = 2.1

[contracts.pool-token]
path = "contracts/pool-token.clar"
epoch = 2.1

[contracts.stackoddpoll]
path = "contracts/stackoddpoll.clar"
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
