[project]
name = "stackodds"
description = "Prototype LMSR-style prediction market on Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.so-token]
path = "contracts/token.clar"
epoch = 2.1

[contracts.stackodds]
path = "contracts/contract.clar"
epoch = 2.1

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
